// Globals

export const nonDraggable = {
  spacer: {
    children: [],
    id: "",
    componentName: "baseSpacer",
    icon: "mdi-format-line-spacing",
    type: "spacer",
    text: "spacer",
    typeDescription: "spacer",
    options: {
      grid: 12,
      active: false,
      height: 30,
      backgroundColor: "white",
    },
  },

  layout: {
    id: "",
    children: [],
    componentName: "baseLayout",
    icon: "mdi-card",
    type: "layout",
    typeDescription: "Layout",
    text: "Layout",
    options: {
      grid: 12,
      flat: false,
      tile: false,
      color: "#FFFFFFFF",
      backgroundColor: "#FFFFFFFF",
      fillHeight: false,
      heightSm: "200",
      heightMd: "200",
      heightLg: "200",
      active: false,
      cropLeft: 0,
      cropTop: 0,
      cropBottom: 0,
      cropRight: 0,
    },
  },
};

export const forms = {
  textField: {
    id: "",
    componentName: "baseTextField",
    icon: "mdi-tooltip-text-outline",
    type: "textField",
    typeDescription: "text field",
    text: "Fält",
    hovered: false,
    options: {
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "Text field",
      color: "#000",
      backgroundColor: "#FFFFFFFF",
      dark: false,
    },
  },
  textArea: {
    id: "",
    componentName: "baseTextArea",
    icon: "mdi-tooltip-text-outline",
    type: "textArea",
    typeDescription: "text area",
    text: "Textarea",
    hovered: false,
    options: {
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "Text area",
      color: "#000",
      backgroundColor: "#FFFFFFFF",
      dark: false,
    },
  },
  checkbox: {
    id: "",
    componentName: "BaseCheckbox",
    icon: "mdi-checkbox-blank-outline",
    type: "checkbox",
    typeDescription: "checkbox",
    text: "checkbox",
    hovered: false,
    options: {
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "checkbox",
      color: "#000",
      dark: false,
      value: "default",
    },
  },

  radioGroup: {
    id: "",
    componentName: "BaseRadioGroup",
    icon: "mdi-radiobox-marked",
    type: "radioGroup",
    typeDescription: "Radio options",
    text: "Radio",
    hovered: false,
    options: {
      type: "Radio",
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "Radio 1",
      color: "#000",
      dark: false,
      value: "default",
      multipleElements: ["Radio 1"],
      radioColumn: false,
    },
  },

  BaseSwitch: {
    id: "",
    componentName: "BaseSwitch",
    icon: "mdi-toggle-switch-off-outline",
    type: "BaseSwitch",
    typeDescription: "switch",
    text: "Switch",
    hovered: false,
    options: {
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "Switch",
      color: "#000",
      dark: false,
      value: "value",
    },
  },

  BaseSelect: {
    id: "",
    componentName: "BaseSelect",
    icon: "mdi-form-dropdown",
    type: "BaseSelect",
    typeDescription: "Select dropdown",
    text: "Dropdown",
    hovered: false,
    options: {
      type: "Dropdown",
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "Option 1",
      color: "#000",
      dark: false,
      value: "default",
      multipleElements: ["Option 1"],
    },
  },

  BaseAutocomplete: {
    id: "",
    componentName: "BaseAutocomplete",
    icon: "mdi-form-dropdown",
    type: "BaseAutocomplete",
    typeDescription: "Autocomplete dropdown",
    text: "Autocomplete",
    hovered: false,
    options: {
      type: "Autocomplete",
      align: "start",
      grid: 6,
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      solo: true,
      elementText: "Option 1",
      color: "#000",
      dark: false,
      value: "default",
      multipleElements: ["Option 1"],
    },
  },
};

export const elements = {
  socialIcons: {
    id: "",
    componentName: "baseSocialIcons",
    icon: "mdi-share-variant",
    type: "socialIcons",
    text: "Social Icons",
    typeDescription: "Social Icons",
    hovered: false,
    options: {
      icons: [
        {
          id: "facebook",
          icon: "mdi-facebook",
          name: "Facebook",
          url: "",
          visible: true,
        },
        {
          id: "github",
          icon: "mdi-github",
          name: "Github",
          url: "",
          visible: true,
        },
        {
          id: "twitter",
          icon: "mdi-twitter",
          name: "Twitter",
          url: "",
          visible: true,
        },
        {
          id: "linkedin",
          icon: "mdi-linkedin",
          name: "Linkedin",
          url: "",
          visible: true,
        },
        {
          id: "instagram",
          icon: "mdi-instagram",
          name: "Instagram",
          url: "",
          visible: true,
        },
      ],
      multipleElementsParams: [],
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
    },
  },

  divider: {
    id: "",
    componentName: "baseDivider",
    icon: "mdi-arrow-split-horizontal",
    type: "divider",
    text: "Divider",
    typeDescription: "Divider",
    hovered: false,
    options: {
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      color: "#0000001f",
    },
  },

  spacer: {
    id: "",
    componentName: "baseSpacerDraggable",
    icon: "mdi-format-line-spacing",
    type: "spacer",
    text: "Skiljelinje",
    typeDescription: "Spacer",
    hovered: false,
    options: {
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      height: "",
      width: "",
      color: "",
    },
  },

  video: {
    id: "",
    componentName: "baseYoutubeVideo",
    icon: "mdi-youtube",
    type: "video",
    text: "YouTube",
    typeDescription: "Video",
    hovered: false,
    options: {
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      videoId: "",
      heightSm: "500",
      heightMd: "500",
      heightLg: "500",
      width: "100%",
    },
  },

  text: {
    id: "",
    componentName: "baseTextAdvanced",
    icon: "mdi-format-text",
    type: "text",
    text: "Text",
    typeDescription: "text",
    hovered: false,
    options: {
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      flat: false,
      tile: false,
      color: "#000",
      backgroundColor: "#FFFFFFFF",
      elementText: "Skriv din text här...",
      class: "text-body-1",
      align: "start",
      active: false,
      fontSize: 17,
      lineHeight: "1.7",
    },
  },

  button: {
    id: "",
    componentName: "baseButton",
    icon: "mdi-gesture-tap-button",
    type: "button",
    typeDescription: "button",
    text: "Knapp",
    hovered: false,
    options: {
      externalLink: "",
      internalLink: undefined,
      specialAction: "",
      fontSize: 17,
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 7,
      elementText: "Klicka här​",
      tile: false,
      color: "#3E4042",
      backgroundColor: "#F5F5F5",
      heightSm: null,
      heightMd: null,
      heightLg: null,
      appendIcon: "",
      showBorder: true,
    },
  },

  image: {
    id: "",
    componentName: "BaseImg",
    icon: "mdi-image-outline",
    type: "image",
    typeDescription: "image",
    text: "Bild",
    hovered: false,
    options: {
      externalLink: "",
      internalLink: undefined,
      specialAction: "",
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      heightSm: 300,
      heightMd: 300,
      heightLg: 300,
      width: "100%",
      contain: [],
      creditAlign: "end",
      image: {
        image: "",
        metadata: {
          credits: "",
        },
        imageName: "",
        validationErrors: false,
      },
    },
  },

  imageCarousel: {
    id: "",
    componentName: "BaseImgCarousel",
    icon: "mdi-view-carousel-outline",
    type: "imageCarousel",
    typeDescription: "image carousel",
    text: "Carousel",
    hovered: false,
    options: {
      continuous: false,
      cycle: false,
      cycleInterval: 6000,
      hideDelimiters: false,
      hideDelimiterBackground: false,
      showArrows: false,
      showArrowsOnHover: false,
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      heightSm: 300,
      heightMd: 300,
      heightLg: 300,
      width: null,
      images: [],
    },
  },

  imageMasonry: {
    id: "",
    componentName: "BaseImgMasonry",
    icon: "mdi-image-multiple-outline",
    type: "imageMasonry",
    typeDescription: "image masonry",
    text: "Bild Masonry",
    hovered: false,
    options: {
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      heightSm: 300,
      heightMd: 300,
      heightLg: 300,
      width: null,
      images: [],
    },
  },

  expansionPanel: {
    id: "",
    componentName: "BaseExpansionPanel",
    icon: "mdi-view-list",
    type: "expansionPanel",
    typeDescription: "Panels panel",
    text: "Expansion Panel",
    hovered: false,
    options: {
      type: "Expansion",
      align: "start",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 6,
      solo: true,
      elementText: "Panel 1",
      color: "#000",
      dark: false,
      value: "default",
      multipleElements: ["Panel 1"],
      multipleElementsParams: [],
    },
  },

  googleMap: {
    id: 223432432,
    componentName: "BaseGoogleMap",
    icon: "mdi-google-maps",
    type: "googleMap",
    typeDescription: "Google map",
    text: "Google map",
    hovered: false,
    options: {
      type: "Map",
      ml: 0,
      mr: 0,
      mt: 0,
      mb: 0,
      pl: 0,
      pr: 0,
      pt: 0,
      pb: 0,
      grid: 12,
      heightSm: 450,
      heightMd: 450,
      heightLg: 450,
      zoom: 17,
      viewControl: true,
      mapType: true,
      solo: true,
      address: "Kyrkogatan 19, 792 30 Mora",
    },
  },
};
