<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Public\Country;
class CountrySeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {

        $countries = [
            ["id"=>1,"nombre"=>"Afganistán","name"=>"Afghanistan","iso2"=>"AF","iso3"=>"AFG","phone_code"=>"93","deleted_at"=>null],
            ["id"=>2,"nombre"=>"Albania","name"=>"Albania","iso2"=>"AL","iso3"=>"ALB","phone_code"=>"355","deleted_at"=>null],
            ["id"=>3,"nombre"=>"Alemania","name"=>"Germany","iso2"=>"DE","iso3"=>"DEU","phone_code"=>"49","deleted_at"=>null],
            ["id"=>4,"nombre"=>"Algeria","name"=>"Algeria","iso2"=>"DZ","iso3"=>"DZA","phone_code"=>"213","deleted_at"=>null],
            ["id"=>5,"nombre"=>"Andorra","name"=>"Andorra","iso2"=>"AD","iso3"=>"AND","phone_code"=>"376","deleted_at"=>null],
            ["id"=>6,"nombre"=>"Angola","name"=>"Angola","iso2"=>"AO","iso3"=>"AGO","phone_code"=>"244","deleted_at"=>null],
            ["id"=>7,"nombre"=>"Anguila","name"=>"Anguilla","iso2"=>"AI","iso3"=>"AIA","phone_code"=>"1264","deleted_at"=>null],
            ["id"=>8,"nombre"=>"Antártida","name"=>"Antarctica","iso2"=>"AQ","iso3"=>"ATA","phone_code"=>"672","deleted_at"=>null],
            ["id"=>9,"nombre"=>"Antigua y Barbuda","name"=>"Antigua and Barbuda","iso2"=>"AG","iso3"=>"ATG","phone_code"=>"1268","deleted_at"=>null],
            ["id"=>10,"nombre"=>"Antillas Neerlandesas","name"=>"Netherlands Antilles","iso2"=>"AN","iso3"=>"ANT","phone_code"=>"599","deleted_at"=>null],
            ["id"=>11,"nombre"=>"Arabia Saudita","name"=>"Saudi Arabia","iso2"=>"SA","iso3"=>"SAU","phone_code"=>"966","deleted_at"=>null],
            ["id"=>12,"nombre"=>"Argentina","name"=>"Argentina","iso2"=>"AR","iso3"=>"ARG","phone_code"=>"54","deleted_at"=>null],
            ["id"=>13,"nombre"=>"Armenia","name"=>"Armenia","iso2"=>"AM","iso3"=>"ARM","phone_code"=>"374","deleted_at"=>null],
            ["id"=>14,"nombre"=>"Aruba","name"=>"Aruba","iso2"=>"AW","iso3"=>"ABW","phone_code"=>"297","deleted_at"=>null],
            ["id"=>15,"nombre"=>"Australia","name"=>"Australia","iso2"=>"AU","iso3"=>"AUS","phone_code"=>"61","deleted_at"=>null],
            ["id"=>16,"nombre"=>"Austria","name"=>"Austria","iso2"=>"AT","iso3"=>"AUT","phone_code"=>"43","deleted_at"=>null],
            ["id"=>17,"nombre"=>"Azerbayán","name"=>"Azerbaijan","iso2"=>"AZ","iso3"=>"AZE","phone_code"=>"994","deleted_at"=>null],
            ["id"=>18,"nombre"=>"Bélgica","name"=>"Belgium","iso2"=>"BE","iso3"=>"BEL","phone_code"=>"32","deleted_at"=>null],
            ["id"=>19,"nombre"=>"Bahamas","name"=>"Bahamas","iso2"=>"BS","iso3"=>"BHS","phone_code"=>"1242","deleted_at"=>null],
            ["id"=>20,"nombre"=>"Bahrein","name"=>"Bahrain","iso2"=>"BH","iso3"=>"BHR","phone_code"=>"973","deleted_at"=>null],
            ["id"=>21,"nombre"=>"Bangladesh","name"=>"Bangladesh","iso2"=>"BD","iso3"=>"BGD","phone_code"=>"880","deleted_at"=>null],
            ["id"=>22,"nombre"=>"Barbados","name"=>"Barbados","iso2"=>"BB","iso3"=>"BRB","phone_code"=>"1246","deleted_at"=>null],
            ["id"=>23,"nombre"=>"Belice","name"=>"Belize","iso2"=>"BZ","iso3"=>"BLZ","phone_code"=>"501","deleted_at"=>null],
            ["id"=>24,"nombre"=>"Benín","name"=>"Benin","iso2"=>"BJ","iso3"=>"BEN","phone_code"=>"229","deleted_at"=>null],
            ["id"=>25,"nombre"=>"Bhután","name"=>"Bhutan","iso2"=>"BT","iso3"=>"BTN","phone_code"=>"975","deleted_at"=>null],
            ["id"=>26,"nombre"=>"Bielorrusia","name"=>"Belarus","iso2"=>"BY","iso3"=>"BLR","phone_code"=>"375","deleted_at"=>null],
            ["id"=>27,"nombre"=>"Birmania","name"=>"Myanmar","iso2"=>"MM","iso3"=>"MMR","phone_code"=>"95","deleted_at"=>null],
            ["id"=>28,"nombre"=>"Bolivia","name"=>"Bolivia","iso2"=>"BO","iso3"=>"BOL","phone_code"=>"591","deleted_at"=>null],
            ["id"=>29,"nombre"=>"Bosnia y Herzegovina","name"=>"Bosnia and Herzegovina","iso2"=>"BA","iso3"=>"BIH","phone_code"=>"387","deleted_at"=>null],
            ["id"=>30,"nombre"=>"Botsuana","name"=>"Botswana","iso2"=>"BW","iso3"=>"BWA","phone_code"=>"267","deleted_at"=>null],
            ["id"=>31,"nombre"=>"Brasil","name"=>"Brazil","iso2"=>"BR","iso3"=>"BRA","phone_code"=>"55","deleted_at"=>null],
            ["id"=>32,"nombre"=>"Brunéi","name"=>"Brunei","iso2"=>"BN","iso3"=>"BRN","phone_code"=>"673","deleted_at"=>null],
            ["id"=>33,"nombre"=>"Bulgaria","name"=>"Bulgaria","iso2"=>"BG","iso3"=>"BGR","phone_code"=>"359","deleted_at"=>null],
            ["id"=>34,"nombre"=>"Burkina Faso","name"=>"Burkina Faso","iso2"=>"BF","iso3"=>"BFA","phone_code"=>"226","deleted_at"=>null],
            ["id"=>35,"nombre"=>"Burundi","name"=>"Burundi","iso2"=>"BI","iso3"=>"BDI","phone_code"=>"257","deleted_at"=>null],
            ["id"=>36,"nombre"=>"Cabo Verde","name"=>"Cape Verde","iso2"=>"CV","iso3"=>"CPV","phone_code"=>"238","deleted_at"=>null],
            ["id"=>37,"nombre"=>"Camboya","name"=>"Cambodia","iso2"=>"KH","iso3"=>"KHM","phone_code"=>"855","deleted_at"=>null],
            ["id"=>38,"nombre"=>"Camerún","name"=>"Cameroon","iso2"=>"CM","iso3"=>"CMR","phone_code"=>"237","deleted_at"=>null],
            ["id"=>39,"nombre"=>"Canadá","name"=>"Canada","iso2"=>"CA","iso3"=>"CAN","phone_code"=>"1","deleted_at"=>null],
            ["id"=>40,"nombre"=>"Chad","name"=>"Chad","iso2"=>"TD","iso3"=>"TCD","phone_code"=>"235","deleted_at"=>null],
            ["id"=>41,"nombre"=>"Chile","name"=>"Chile","iso2"=>"CL","iso3"=>"CHL","phone_code"=>"56","deleted_at"=>null],
            ["id"=>42,"nombre"=>"China","name"=>"China","iso2"=>"CN","iso3"=>"CHN","phone_code"=>"86","deleted_at"=>null],
            ["id"=>43,"nombre"=>"Chipre","name"=>"Cyprus","iso2"=>"CY","iso3"=>"CYP","phone_code"=>"357","deleted_at"=>null],
            ["id"=>44,"nombre"=>"Ciudad del Vaticano","name"=>"Vatican City State","iso2"=>"VA","iso3"=>"VAT","phone_code"=>"39","deleted_at"=>null],
            ["id"=>45,"nombre"=>"Colombia","name"=>"Colombia","iso2"=>"CO","iso3"=>"COL","phone_code"=>"57","deleted_at"=>null],
            ["id"=>46,"nombre"=>"Comoras","name"=>"Comoros","iso2"=>"KM","iso3"=>"COM","phone_code"=>"269","deleted_at"=>null],
            ["id"=>47,"nombre"=>"Congo","name"=>"Congo","iso2"=>"CG","iso3"=>"COG","phone_code"=>"242","deleted_at"=>null],
            ["id"=>48,"nombre"=>"Congo","name"=>"Congo","iso2"=>"CD","iso3"=>"COD","phone_code"=>"243","deleted_at"=>null],
            ["id"=>49,"nombre"=>"Corea del Norte","name"=>"North Korea","iso2"=>"KP","iso3"=>"PRK","phone_code"=>"850","deleted_at"=>null],
            ["id"=>50,"nombre"=>"Corea del Sur","name"=>"South Korea","iso2"=>"KR","iso3"=>"KOR","phone_code"=>"82","deleted_at"=>null],
            ["id"=>51,"nombre"=>"Costa de Marfil","name"=>"Ivory Coast","iso2"=>"CI","iso3"=>"CIV","phone_code"=>"225","deleted_at"=>null],
            ["id"=>52,"nombre"=>"Costa Rica","name"=>"Costa Rica","iso2"=>"CR","iso3"=>"CRI","phone_code"=>"506","deleted_at"=>null],
            ["id"=>53,"nombre"=>"Croacia","name"=>"Croatia","iso2"=>"HR","iso3"=>"HRV","phone_code"=>"385","deleted_at"=>null],
            ["id"=>54,"nombre"=>"Cuba","name"=>"Cuba","iso2"=>"CU","iso3"=>"CUB","phone_code"=>"53","deleted_at"=>null],
            ["id"=>55,"nombre"=>"Dinamarca","name"=>"Denmark","iso2"=>"DK","iso3"=>"DNK","phone_code"=>"45","deleted_at"=>null],
            ["id"=>56,"nombre"=>"Dominica","name"=>"Dominica","iso2"=>"DM","iso3"=>"DMA","phone_code"=>"1767","deleted_at"=>null],
            ["id"=>57,"nombre"=>"Ecuador","name"=>"Ecuador","iso2"=>"EC","iso3"=>"ECU","phone_code"=>"593","deleted_at"=>null],
            ["id"=>58,"nombre"=>"Egipto","name"=>"Egypt","iso2"=>"EG","iso3"=>"EGY","phone_code"=>"20","deleted_at"=>null],
            ["id"=>59,"nombre"=>"El Salvador","name"=>"El Salvador","iso2"=>"SV","iso3"=>"SLV","phone_code"=>"503","deleted_at"=>null],
            ["id"=>60,"nombre"=>"Emiratos Árabes Unidos","name"=>"United Arab Emirates","iso2"=>"AE","iso3"=>"ARE","phone_code"=>"971","deleted_at"=>null],
            ["id"=>61,"nombre"=>"Eritrea","name"=>"Eritrea","iso2"=>"ER","iso3"=>"ERI","phone_code"=>"291","deleted_at"=>null],
            ["id"=>62,"nombre"=>"Eslovaquia","name"=>"Slovakia","iso2"=>"SK","iso3"=>"SVK","phone_code"=>"421","deleted_at"=>null],
            ["id"=>63,"nombre"=>"Eslovenia","name"=>"Slovenia","iso2"=>"SI","iso3"=>"SVN","phone_code"=>"386","deleted_at"=>null],
            ["id"=>64,"nombre"=>"España","name"=>"Spain","iso2"=>"ES","iso3"=>"ESP","phone_code"=>"34","deleted_at"=>null],
            ["id"=>65,"nombre"=>"Estados Unidos de América","name"=>"United States of America","iso2"=>"US","iso3"=>"USA","phone_code"=>"1","deleted_at"=>null],
            ["id"=>66,"nombre"=>"Estonia","name"=>"Estonia","iso2"=>"EE","iso3"=>"EST","phone_code"=>"372","deleted_at"=>null],
            ["id"=>67,"nombre"=>"Etiopía","name"=>"Ethiopia","iso2"=>"ET","iso3"=>"ETH","phone_code"=>"251","deleted_at"=>null],
            ["id"=>68,"nombre"=>"Filipinas","name"=>"Philippines","iso2"=>"PH","iso3"=>"PHL","phone_code"=>"63","deleted_at"=>null],
            ["id"=>69,"nombre"=>"Finlandia","name"=>"Finland","iso2"=>"FI","iso3"=>"FIN","phone_code"=>"358","deleted_at"=>null],
            ["id"=>70,"nombre"=>"Fiyi","name"=>"Fiji","iso2"=>"FJ","iso3"=>"FJI","phone_code"=>"679","deleted_at"=>null],
            ["id"=>71,"nombre"=>"Francia","name"=>"France","iso2"=>"FR","iso3"=>"FRA","phone_code"=>"33","deleted_at"=>null],
            ["id"=>72,"nombre"=>"Gabón","name"=>"Gabon","iso2"=>"GA","iso3"=>"GAB","phone_code"=>"241","deleted_at"=>null],
            ["id"=>73,"nombre"=>"Gambia","name"=>"Gambia","iso2"=>"GM","iso3"=>"GMB","phone_code"=>"220","deleted_at"=>null],
            ["id"=>74,"nombre"=>"Georgia","name"=>"Georgia","iso2"=>"GE","iso3"=>"GEO","phone_code"=>"995","deleted_at"=>null],
            ["id"=>75,"nombre"=>"Ghana","name"=>"Ghana","iso2"=>"GH","iso3"=>"GHA","phone_code"=>"233","deleted_at"=>null],
            ["id"=>76,"nombre"=>"Gibraltar","name"=>"Gibraltar","iso2"=>"GI","iso3"=>"GIB","phone_code"=>"350","deleted_at"=>null],
            ["id"=>77,"nombre"=>"Granada","name"=>"Grenada","iso2"=>"GD","iso3"=>"GRD","phone_code"=>"1473","deleted_at"=>null],
            ["id"=>78,"nombre"=>"Grecia","name"=>"Greece","iso2"=>"GR","iso3"=>"GRC","phone_code"=>"30","deleted_at"=>null],
            ["id"=>79,"nombre"=>"Groenlandia","name"=>"Greenland","iso2"=>"GL","iso3"=>"GRL","phone_code"=>"299","deleted_at"=>null],
            ["id"=>80,"nombre"=>"Guadalupe","name"=>"Guadeloupe","iso2"=>"GP","iso3"=>"GLP","phone_code"=>"","deleted_at"=>null],
            ["id"=>81,"nombre"=>"Guam","name"=>"Guam","iso2"=>"GU","iso3"=>"GUM","phone_code"=>"1671","deleted_at"=>null],
            ["id"=>82,"nombre"=>"Guatemala","name"=>"Guatemala","iso2"=>"GT","iso3"=>"GTM","phone_code"=>"502","deleted_at"=>null],
            ["id"=>83,"nombre"=>"Guayana Francesa","name"=>"French Guiana","iso2"=>"GF","iso3"=>"GUF","phone_code"=>"","deleted_at"=>null],
            ["id"=>84,"nombre"=>"Guernsey","name"=>"Guernsey","iso2"=>"GG","iso3"=>"GGY","phone_code"=>"","deleted_at"=>null],
            ["id"=>85,"nombre"=>"Guinea","name"=>"Guinea","iso2"=>"GN","iso3"=>"GIN","phone_code"=>"224","deleted_at"=>null],
            ["id"=>86,"nombre"=>"Guinea Ecuatorial","name"=>"Equatorial Guinea","iso2"=>"GQ","iso3"=>"GNQ","phone_code"=>"240","deleted_at"=>null],
            ["id"=>87,"nombre"=>"Guinea-Bissau","name"=>"Guinea-Bissau","iso2"=>"GW","iso3"=>"GNB","phone_code"=>"245","deleted_at"=>null],
            ["id"=>88,"nombre"=>"Guyana","name"=>"Guyana","iso2"=>"GY","iso3"=>"GUY","phone_code"=>"592","deleted_at"=>null],
            ["id"=>89,"nombre"=>"Haití","name"=>"Haiti","iso2"=>"HT","iso3"=>"HTI","phone_code"=>"509","deleted_at"=>null],
            ["id"=>90,"nombre"=>"Honduras","name"=>"Honduras","iso2"=>"HN","iso3"=>"HND","phone_code"=>"504","deleted_at"=>null],
            ["id"=>91,"nombre"=>"Hong kong","name"=>"Hong Kong","iso2"=>"HK","iso3"=>"HKG","phone_code"=>"852","deleted_at"=>null],
            ["id"=>92,"nombre"=>"Hungría","name"=>"Hungary","iso2"=>"HU","iso3"=>"HUN","phone_code"=>"36","deleted_at"=>null],
            ["id"=>93,"nombre"=>"India","name"=>"India","iso2"=>"IN","iso3"=>"IND","phone_code"=>"91","deleted_at"=>null],
            ["id"=>94,"nombre"=>"Indonesia","name"=>"Indonesia","iso2"=>"ID","iso3"=>"IDN","phone_code"=>"62","deleted_at"=>null],
            ["id"=>95,"nombre"=>"Irán","name"=>"Iran","iso2"=>"IR","iso3"=>"IRN","phone_code"=>"98","deleted_at"=>null],
            ["id"=>96,"nombre"=>"Irak","name"=>"Iraq","iso2"=>"IQ","iso3"=>"IRQ","phone_code"=>"964","deleted_at"=>null],
            ["id"=>97,"nombre"=>"Irlanda","name"=>"Ireland","iso2"=>"IE","iso3"=>"IRL","phone_code"=>"353","deleted_at"=>null],
            ["id"=>98,"nombre"=>"Isla Bouvet","name"=>"Bouvet Island","iso2"=>"BV","iso3"=>"BVT","phone_code"=>"","deleted_at"=>null],
            ["id"=>99,"nombre"=>"Isla de Man","name"=>"Isle of Man","iso2"=>"IM","iso3"=>"IMN","phone_code"=>"44","deleted_at"=>null],
            ["id"=>100,"nombre"=>"Isla de Navidad","name"=>"Christmas Island","iso2"=>"CX","iso3"=>"CXR","phone_code"=>"61","deleted_at"=>null],
            ["id"=>101,"nombre"=>"Isla Norfolk","name"=>"Norfolk Island","iso2"=>"NF","iso3"=>"NFK","phone_code"=>"","deleted_at"=>null],
            ["id"=>102,"nombre"=>"Islandia","name"=>"Iceland","iso2"=>"IS","iso3"=>"ISL","phone_code"=>"354","deleted_at"=>null],
            ["id"=>103,"nombre"=>"Islas Bermudas","name"=>"Bermuda Islands","iso2"=>"BM","iso3"=>"BMU","phone_code"=>"1441","deleted_at"=>null],
            ["id"=>104,"nombre"=>"Islas Caimán","name"=>"Cayman Islands","iso2"=>"KY","iso3"=>"CYM","phone_code"=>"1345","deleted_at"=>null],
            ["id"=>105,"nombre"=>"Islas Cocos (Keeling)","name"=>"Cocos (Keeling) Islands","iso2"=>"CC","iso3"=>"CCK","phone_code"=>"61","deleted_at"=>null],
            ["id"=>106,"nombre"=>"Islas Cook","name"=>"Cook Islands","iso2"=>"CK","iso3"=>"COK","phone_code"=>"682","deleted_at"=>null],
            ["id"=>107,"nombre"=>"Islas de Åland","name"=>"Åland Islands","iso2"=>"AX","iso3"=>"ALA","phone_code"=>"","deleted_at"=>null],
            ["id"=>108,"nombre"=>"Islas Feroe","name"=>"Faroe Islands","iso2"=>"FO","iso3"=>"FRO","phone_code"=>"298","deleted_at"=>null],
            ["id"=>109,"nombre"=>"Islas Georgias del Sur y Sandwich del Sur","name"=>"South Georgia and the South Sandwich Islands","iso2"=>"GS","iso3"=>"SGS","phone_code"=>"","deleted_at"=>null],
            ["id"=>110,"nombre"=>"Islas Heard y McDonald","name"=>"Heard Island and McDonald Islands","iso2"=>"HM","iso3"=>"HMD","phone_code"=>"","deleted_at"=>null],
            ["id"=>111,"nombre"=>"Islas Maldivas","name"=>"Maldives","iso2"=>"MV","iso3"=>"MDV","phone_code"=>"960","deleted_at"=>null],
            ["id"=>112,"nombre"=>"Islas Malvinas","name"=>"Falkland Islands (Malvinas)","iso2"=>"FK","iso3"=>"FLK","phone_code"=>"500","deleted_at"=>null],
            ["id"=>113,"nombre"=>"Islas Marianas del Norte","name"=>"Northern Mariana Islands","iso2"=>"MP","iso3"=>"MNP","phone_code"=>"1670","deleted_at"=>null],
            ["id"=>114,"nombre"=>"Islas Marshall","name"=>"Marshall Islands","iso2"=>"MH","iso3"=>"MHL","phone_code"=>"692","deleted_at"=>null],
            ["id"=>115,"nombre"=>"Islas Pitcairn","name"=>"Pitcairn Islands","iso2"=>"PN","iso3"=>"PCN","phone_code"=>"870","deleted_at"=>null],
            ["id"=>116,"nombre"=>"Islas Salomón","name"=>"Solomon Islands","iso2"=>"SB","iso3"=>"SLB","phone_code"=>"677","deleted_at"=>null],
            ["id"=>117,"nombre"=>"Islas Turcas y Caicos","name"=>"Turks and Caicos Islands","iso2"=>"TC","iso3"=>"TCA","phone_code"=>"1649","deleted_at"=>null],
            ["id"=>118,"nombre"=>"Islas Ultramarinas Menores de Estados Unidos","name"=>"United States Minor Outlying Islands","iso2"=>"UM","iso3"=>"UMI","phone_code"=>"","deleted_at"=>null],
            ["id"=>119,"nombre"=>"Islas Vírgenes Británicas","name"=>"Virgin Islands","iso2"=>"VG","iso3"=>"VG","phone_code"=>"1284","deleted_at"=>null],
            ["id"=>120,"nombre"=>"Islas Vírgenes de los Estados Unidos","name"=>"United States Virgin Islands","iso2"=>"VI","iso3"=>"VIR","phone_code"=>"1340","deleted_at"=>null],
            ["id"=>121,"nombre"=>"Israel","name"=>"Israel","iso2"=>"IL","iso3"=>"ISR","phone_code"=>"972","deleted_at"=>null],
            ["id"=>122,"nombre"=>"Italia","name"=>"Italy","iso2"=>"IT","iso3"=>"ITA","phone_code"=>"39","deleted_at"=>null],
            ["id"=>123,"nombre"=>"Jamaica","name"=>"Jamaica","iso2"=>"JM","iso3"=>"JAM","phone_code"=>"1876","deleted_at"=>null],
            ["id"=>124,"nombre"=>"Japón","name"=>"Japan","iso2"=>"JP","iso3"=>"JPN","phone_code"=>"81","deleted_at"=>null],
            ["id"=>125,"nombre"=>"Jersey","name"=>"Jersey","iso2"=>"JE","iso3"=>"JEY","phone_code"=>"","deleted_at"=>null],
            ["id"=>126,"nombre"=>"Jordania","name"=>"Jordan","iso2"=>"JO","iso3"=>"JOR","phone_code"=>"962","deleted_at"=>null],
            ["id"=>127,"nombre"=>"Kazajistán","name"=>"Kazakhstan","iso2"=>"KZ","iso3"=>"KAZ","phone_code"=>"7","deleted_at"=>null],
            ["id"=>128,"nombre"=>"Kenia","name"=>"Kenya","iso2"=>"KE","iso3"=>"KEN","phone_code"=>"254","deleted_at"=>null],
            ["id"=>129,"nombre"=>"Kirgizstán","name"=>"Kyrgyzstan","iso2"=>"KG","iso3"=>"KGZ","phone_code"=>"996","deleted_at"=>null],
            ["id"=>130,"nombre"=>"Kiribati","name"=>"Kiribati","iso2"=>"KI","iso3"=>"KIR","phone_code"=>"686","deleted_at"=>null],
            ["id"=>131,"nombre"=>"Kuwait","name"=>"Kuwait","iso2"=>"KW","iso3"=>"KWT","phone_code"=>"965","deleted_at"=>null],
            ["id"=>132,"nombre"=>"Líbano","name"=>"Lebanon","iso2"=>"LB","iso3"=>"LBN","phone_code"=>"961","deleted_at"=>null],
            ["id"=>133,"nombre"=>"Laos","name"=>"Laos","iso2"=>"LA","iso3"=>"LAO","phone_code"=>"856","deleted_at"=>null],
            ["id"=>134,"nombre"=>"Lesoto","name"=>"Lesotho","iso2"=>"LS","iso3"=>"LSO","phone_code"=>"266","deleted_at"=>null],
            ["id"=>135,"nombre"=>"Letonia","name"=>"Latvia","iso2"=>"LV","iso3"=>"LVA","phone_code"=>"371","deleted_at"=>null],
            ["id"=>136,"nombre"=>"Liberia","name"=>"Liberia","iso2"=>"LR","iso3"=>"LBR","phone_code"=>"231","deleted_at"=>null],
            ["id"=>137,"nombre"=>"Libia","name"=>"Libya","iso2"=>"LY","iso3"=>"LBY","phone_code"=>"218","deleted_at"=>null],
            ["id"=>138,"nombre"=>"Liechtenstein","name"=>"Liechtenstein","iso2"=>"LI","iso3"=>"LIE","phone_code"=>"423","deleted_at"=>null],
            ["id"=>139,"nombre"=>"Lituania","name"=>"Lithuania","iso2"=>"LT","iso3"=>"LTU","phone_code"=>"370","deleted_at"=>null],
            ["id"=>140,"nombre"=>"Luxemburgo","name"=>"Luxembourg","iso2"=>"LU","iso3"=>"LUX","phone_code"=>"352","deleted_at"=>null],
            ["id"=>141,"nombre"=>"México","name"=>"Mexico","iso2"=>"MX","iso3"=>"MEX","phone_code"=>"52","deleted_at"=>null],
            ["id"=>142,"nombre"=>"Mónaco","name"=>"Monaco","iso2"=>"MC","iso3"=>"MCO","phone_code"=>"377","deleted_at"=>null],
            ["id"=>143,"nombre"=>"Macao","name"=>"Macao","iso2"=>"MO","iso3"=>"MAC","phone_code"=>"853","deleted_at"=>null],
            ["id"=>144,"nombre"=>"Macedônia","name"=>"Macedonia","iso2"=>"MK","iso3"=>"MKD","phone_code"=>"389","deleted_at"=>null],
            ["id"=>145,"nombre"=>"Madagascar","name"=>"Madagascar","iso2"=>"MG","iso3"=>"MDG","phone_code"=>"261","deleted_at"=>null],
            ["id"=>146,"nombre"=>"Malasia","name"=>"Malaysia","iso2"=>"MY","iso3"=>"MYS","phone_code"=>"60","deleted_at"=>null],
            ["id"=>147,"nombre"=>"Malawi","name"=>"Malawi","iso2"=>"MW","iso3"=>"MWI","phone_code"=>"265","deleted_at"=>null],
            ["id"=>148,"nombre"=>"Mali","name"=>"Mali","iso2"=>"ML","iso3"=>"MLI","phone_code"=>"223","deleted_at"=>null],
            ["id"=>149,"nombre"=>"Malta","name"=>"Malta","iso2"=>"MT","iso3"=>"MLT","phone_code"=>"356","deleted_at"=>null],
            ["id"=>150,"nombre"=>"Marruecos","name"=>"Morocco","iso2"=>"MA","iso3"=>"MAR","phone_code"=>"212","deleted_at"=>null],
            ["id"=>151,"nombre"=>"Martinica","name"=>"Martinique","iso2"=>"MQ","iso3"=>"MTQ","phone_code"=>"","deleted_at"=>null],
            ["id"=>152,"nombre"=>"Mauricio","name"=>"Mauritius","iso2"=>"MU","iso3"=>"MUS","phone_code"=>"230","deleted_at"=>null],
            ["id"=>153,"nombre"=>"Mauritania","name"=>"Mauritania","iso2"=>"MR","iso3"=>"MRT","phone_code"=>"222","deleted_at"=>null],
            ["id"=>154,"nombre"=>"Mayotte","name"=>"Mayotte","iso2"=>"YT","iso3"=>"MYT","phone_code"=>"262","deleted_at"=>null],
            ["id"=>155,"nombre"=>"Micronesia","name"=>"Estados Federados de","iso2"=>"FM","iso3"=>"FSM","phone_code"=>"691","deleted_at"=>null],
            ["id"=>156,"nombre"=>"Moldavia","name"=>"Moldova","iso2"=>"MD","iso3"=>"MDA","phone_code"=>"373","deleted_at"=>null],
            ["id"=>157,"nombre"=>"Mongolia","name"=>"Mongolia","iso2"=>"MN","iso3"=>"MNG","phone_code"=>"976","deleted_at"=>null],
            ["id"=>158,"nombre"=>"Montenegro","name"=>"Montenegro","iso2"=>"ME","iso3"=>"MNE","phone_code"=>"382","deleted_at"=>null],
            ["id"=>159,"nombre"=>"Montserrat","name"=>"Montserrat","iso2"=>"MS","iso3"=>"MSR","phone_code"=>"1664","deleted_at"=>null],
            ["id"=>160,"nombre"=>"Mozambique","name"=>"Mozambique","iso2"=>"MZ","iso3"=>"MOZ","phone_code"=>"258","deleted_at"=>null],
            ["id"=>161,"nombre"=>"Namibia","name"=>"Namibia","iso2"=>"NA","iso3"=>"NAM","phone_code"=>"264","deleted_at"=>null],
            ["id"=>162,"nombre"=>"Nauru","name"=>"Nauru","iso2"=>"NR","iso3"=>"NRU","phone_code"=>"674","deleted_at"=>null],
            ["id"=>163,"nombre"=>"Nepal","name"=>"Nepal","iso2"=>"NP","iso3"=>"NPL","phone_code"=>"977","deleted_at"=>null],
            ["id"=>164,"nombre"=>"Nicaragua","name"=>"Nicaragua","iso2"=>"NI","iso3"=>"NIC","phone_code"=>"505","deleted_at"=>null],
            ["id"=>165,"nombre"=>"Niger","name"=>"Niger","iso2"=>"NE","iso3"=>"NER","phone_code"=>"227","deleted_at"=>null],
            ["id"=>166,"nombre"=>"Nigeria","name"=>"Nigeria","iso2"=>"NG","iso3"=>"NGA","phone_code"=>"234","deleted_at"=>null],
            ["id"=>167,"nombre"=>"Niue","name"=>"Niue","iso2"=>"NU","iso3"=>"NIU","phone_code"=>"683","deleted_at"=>null],
            ["id"=>168,"nombre"=>"Noruega","name"=>"Norway","iso2"=>"NO","iso3"=>"NOR","phone_code"=>"47","deleted_at"=>null],
            ["id"=>169,"nombre"=>"Nueva Caledonia","name"=>"New Caledonia","iso2"=>"NC","iso3"=>"NCL","phone_code"=>"687","deleted_at"=>null],
            ["id"=>170,"nombre"=>"Nueva Zelanda","name"=>"New Zealand","iso2"=>"NZ","iso3"=>"NZL","phone_code"=>"64","deleted_at"=>null],
            ["id"=>171,"nombre"=>"Omán","name"=>"Oman","iso2"=>"OM","iso3"=>"OMN","phone_code"=>"968","deleted_at"=>null],
            ["id"=>172,"nombre"=>"Países Bajos","name"=>"Netherlands","iso2"=>"NL","iso3"=>"NLD","phone_code"=>"31","deleted_at"=>null],
            ["id"=>173,"nombre"=>"Pakistán","name"=>"Pakistan","iso2"=>"PK","iso3"=>"PAK","phone_code"=>"92","deleted_at"=>null],
            ["id"=>174,"nombre"=>"Palau","name"=>"Palau","iso2"=>"PW","iso3"=>"PLW","phone_code"=>"680","deleted_at"=>null],
            ["id"=>175,"nombre"=>"Palestina","name"=>"Palestine","iso2"=>"PS","iso3"=>"PSE","phone_code"=>"","deleted_at"=>null],
            ["id"=>176,"nombre"=>"Panamá","name"=>"Panama","iso2"=>"PA","iso3"=>"PAN","phone_code"=>"507","deleted_at"=>null],
            ["id"=>177,"nombre"=>"Papúa Nueva Guinea","name"=>"Papua New Guinea","iso2"=>"PG","iso3"=>"PNG","phone_code"=>"675","deleted_at"=>null],
            ["id"=>178,"nombre"=>"Paraguay","name"=>"Paraguay","iso2"=>"PY","iso3"=>"PRY","phone_code"=>"595","deleted_at"=>null],
            ["id"=>179,"nombre"=>"Perú","name"=>"Peru","iso2"=>"PE","iso3"=>"PER","phone_code"=>"51","deleted_at"=>null],
            ["id"=>180,"nombre"=>"Polinesia Francesa","name"=>"French Polynesia","iso2"=>"PF","iso3"=>"PYF","phone_code"=>"689","deleted_at"=>null],
            ["id"=>181,"nombre"=>"Polonia","name"=>"Poland","iso2"=>"PL","iso3"=>"POL","phone_code"=>"48","deleted_at"=>null],
            ["id"=>182,"nombre"=>"Portugal","name"=>"Portugal","iso2"=>"PT","iso3"=>"PRT","phone_code"=>"351","deleted_at"=>null],
            ["id"=>183,"nombre"=>"Puerto Rico","name"=>"Puerto Rico","iso2"=>"PR","iso3"=>"PRI","phone_code"=>"1","deleted_at"=>null],
            ["id"=>184,"nombre"=>"Qatar","name"=>"Qatar","iso2"=>"QA","iso3"=>"QAT","phone_code"=>"974","deleted_at"=>null],
            ["id"=>185,"nombre"=>"Reino Unido","name"=>"United Kingdom","iso2"=>"GB","iso3"=>"GBR","phone_code"=>"44","deleted_at"=>null],
            ["id"=>186,"nombre"=>"República Centroafricana","name"=>"Central African Republic","iso2"=>"CF","iso3"=>"CAF","phone_code"=>"236","deleted_at"=>null],
            ["id"=>187,"nombre"=>"República Checa","name"=>"Czech Republic","iso2"=>"CZ","iso3"=>"CZE","phone_code"=>"420","deleted_at"=>null],
            ["id"=>188,"nombre"=>"República Dominicana","name"=>"Dominican Republic","iso2"=>"DO","iso3"=>"DOM","phone_code"=>"1809","deleted_at"=>null],
            ["id"=>189,"nombre"=>"Reunión","name"=>"Réunion","iso2"=>"RE","iso3"=>"REU","phone_code"=>"","deleted_at"=>null],
            ["id"=>190,"nombre"=>"Ruanda","name"=>"Rwanda","iso2"=>"RW","iso3"=>"RWA","phone_code"=>"250","deleted_at"=>null],
            ["id"=>191,"nombre"=>"Rumanía","name"=>"Romania","iso2"=>"RO","iso3"=>"ROU","phone_code"=>"40","deleted_at"=>null],
            ["id"=>192,"nombre"=>"Rusia","name"=>"Russia","iso2"=>"RU","iso3"=>"RUS","phone_code"=>"7","deleted_at"=>null],
            ["id"=>193,"nombre"=>"Sahara Occidental","name"=>"Western Sahara","iso2"=>"EH","iso3"=>"ESH","phone_code"=>"","deleted_at"=>null],
            ["id"=>194,"nombre"=>"Samoa","name"=>"Samoa","iso2"=>"WS","iso3"=>"WSM","phone_code"=>"685","deleted_at"=>null],
            ["id"=>195,"nombre"=>"Samoa Americana","name"=>"American Samoa","iso2"=>"AS","iso3"=>"ASM","phone_code"=>"1684","deleted_at"=>null],
            ["id"=>196,"nombre"=>"San Bartolomé","name"=>"Saint Barthélemy","iso2"=>"BL","iso3"=>"BLM","phone_code"=>"590","deleted_at"=>null],
            ["id"=>197,"nombre"=>"San Cristóbal y Nieves","name"=>"Saint Kitts and Nevis","iso2"=>"KN","iso3"=>"KNA","phone_code"=>"1869","deleted_at"=>null],
            ["id"=>198,"nombre"=>"San Marino","name"=>"San Marino","iso2"=>"SM","iso3"=>"SMR","phone_code"=>"378","deleted_at"=>null],
            ["id"=>199,"nombre"=>"San Martín (Francia)","name"=>"Saint Martin (French part)","iso2"=>"MF","iso3"=>"MAF","phone_code"=>"1599","deleted_at"=>null],
            ["id"=>200,"nombre"=>"San Pedro y Miquelón","name"=>"Saint Pierre and Miquelon","iso2"=>"PM","iso3"=>"SPM","phone_code"=>"508","deleted_at"=>null],
            ["id"=>201,"nombre"=>"San Vicente y las Granadinas","name"=>"Saint Vincent and the Grenadines","iso2"=>"VC","iso3"=>"VCT","phone_code"=>"1784","deleted_at"=>null],
            ["id"=>202,"nombre"=>"Santa Elena","name"=>"Ascensión y Tristán de Acuña","iso2"=>"SH","iso3"=>"SHN","phone_code"=>"290","deleted_at"=>null],
            ["id"=>203,"nombre"=>"Santa Lucía","name"=>"Saint Lucia","iso2"=>"LC","iso3"=>"LCA","phone_code"=>"1758","deleted_at"=>null],
            ["id"=>204,"nombre"=>"Santo Tomé y Príncipe","name"=>"Sao Tome and Principe","iso2"=>"ST","iso3"=>"STP","phone_code"=>"239","deleted_at"=>null],
            ["id"=>205,"nombre"=>"Senegal","name"=>"Senegal","iso2"=>"SN","iso3"=>"SEN","phone_code"=>"221","deleted_at"=>null],
            ["id"=>206,"nombre"=>"Serbia","name"=>"Serbia","iso2"=>"RS","iso3"=>"SRB","phone_code"=>"381","deleted_at"=>null],
            ["id"=>207,"nombre"=>"Seychelles","name"=>"Seychelles","iso2"=>"SC","iso3"=>"SYC","phone_code"=>"248","deleted_at"=>null],
            ["id"=>208,"nombre"=>"Sierra Leona","name"=>"Sierra Leone","iso2"=>"SL","iso3"=>"SLE","phone_code"=>"232","deleted_at"=>null],
            ["id"=>209,"nombre"=>"Singapur","name"=>"Singapore","iso2"=>"SG","iso3"=>"SGP","phone_code"=>"65","deleted_at"=>null],
            ["id"=>210,"nombre"=>"Siria","name"=>"Syria","iso2"=>"SY","iso3"=>"SYR","phone_code"=>"963","deleted_at"=>null],
            ["id"=>211,"nombre"=>"Somalia","name"=>"Somalia","iso2"=>"SO","iso3"=>"SOM","phone_code"=>"252","deleted_at"=>null],
            ["id"=>212,"nombre"=>"Sri lanka","name"=>"Sri Lanka","iso2"=>"LK","iso3"=>"LKA","phone_code"=>"94","deleted_at"=>null],
            ["id"=>213,"nombre"=>"Sudáfrica","name"=>"South Africa","iso2"=>"ZA","iso3"=>"ZAF","phone_code"=>"27","deleted_at"=>null],
            ["id"=>214,"nombre"=>"Sudán","name"=>"Sudan","iso2"=>"SD","iso3"=>"SDN","phone_code"=>"249","deleted_at"=>null],
            ["id"=>215,"nombre"=>"Suecia","name"=>"Sweden","iso2"=>"SE","iso3"=>"SWE","phone_code"=>"46","deleted_at"=>null],
            ["id"=>216,"nombre"=>"Suiza","name"=>"Switzerland","iso2"=>"CH","iso3"=>"CHE","phone_code"=>"41","deleted_at"=>null],
            ["id"=>217,"nombre"=>"Surinám","name"=>"Suriname","iso2"=>"SR","iso3"=>"SUR","phone_code"=>"597","deleted_at"=>null],
            ["id"=>218,"nombre"=>"Svalbard y Jan Mayen","name"=>"Svalbard and Jan Mayen","iso2"=>"SJ","iso3"=>"SJM","phone_code"=>"","deleted_at"=>null],
            ["id"=>219,"nombre"=>"Swazilandia","name"=>"Swaziland","iso2"=>"SZ","iso3"=>"SWZ","phone_code"=>"268","deleted_at"=>null],
            ["id"=>220,"nombre"=>"Tadjikistán","name"=>"Tajikistan","iso2"=>"TJ","iso3"=>"TJK","phone_code"=>"992","deleted_at"=>null],
            ["id"=>221,"nombre"=>"Tailandia","name"=>"Thailand","iso2"=>"TH","iso3"=>"THA","phone_code"=>"66","deleted_at"=>null],
            ["id"=>222,"nombre"=>"Taiwán","name"=>"Taiwan","iso2"=>"TW","iso3"=>"TWN","phone_code"=>"886","deleted_at"=>null],
            ["id"=>223,"nombre"=>"Tanzania","name"=>"Tanzania","iso2"=>"TZ","iso3"=>"TZA","phone_code"=>"255","deleted_at"=>null],
            ["id"=>224,"nombre"=>"Territorio Británico del Océano Índico","name"=>"British Indian Ocean Territory","iso2"=>"IO","iso3"=>"IOT","phone_code"=>"","deleted_at"=>null],
            ["id"=>225,"nombre"=>"Territorios Australes y Antárticas Franceses","name"=>"French Southern Territories","iso2"=>"TF","iso3"=>"ATF","phone_code"=>"","deleted_at"=>null],
            ["id"=>226,"nombre"=>"Timor Oriental","name"=>"East Timor","iso2"=>"TL","iso3"=>"TLS","phone_code"=>"670","deleted_at"=>null],
            ["id"=>227,"nombre"=>"Togo","name"=>"Togo","iso2"=>"TG","iso3"=>"TGO","phone_code"=>"228","deleted_at"=>null],
            ["id"=>228,"nombre"=>"Tokelau","name"=>"Tokelau","iso2"=>"TK","iso3"=>"TKL","phone_code"=>"690","deleted_at"=>null],
            ["id"=>229,"nombre"=>"Tonga","name"=>"Tonga","iso2"=>"TO","iso3"=>"TON","phone_code"=>"676","deleted_at"=>null],
            ["id"=>230,"nombre"=>"Trinidad y Tobago","name"=>"Trinidad and Tobago","iso2"=>"TT","iso3"=>"TTO","phone_code"=>"1868","deleted_at"=>null],
            ["id"=>231,"nombre"=>"Tunez","name"=>"Tunisia","iso2"=>"TN","iso3"=>"TUN","phone_code"=>"216","deleted_at"=>null],
            ["id"=>232,"nombre"=>"Turkmenistán","name"=>"Turkmenistan","iso2"=>"TM","iso3"=>"TKM","phone_code"=>"993","deleted_at"=>null],
            ["id"=>233,"nombre"=>"Turquía","name"=>"Turkey","iso2"=>"TR","iso3"=>"TUR","phone_code"=>"90","deleted_at"=>null],
            ["id"=>234,"nombre"=>"Tuvalu","name"=>"Tuvalu","iso2"=>"TV","iso3"=>"TUV","phone_code"=>"688","deleted_at"=>null],
            ["id"=>235,"nombre"=>"Ucrania","name"=>"Ukraine","iso2"=>"UA","iso3"=>"UKR","phone_code"=>"380","deleted_at"=>null],
            ["id"=>236,"nombre"=>"Uganda","name"=>"Uganda","iso2"=>"UG","iso3"=>"UGA","phone_code"=>"256","deleted_at"=>null],
            ["id"=>237,"nombre"=>"Uruguay","name"=>"Uruguay","iso2"=>"UY","iso3"=>"URY","phone_code"=>"598","deleted_at"=>null],
            ["id"=>238,"nombre"=>"Uzbekistán","name"=>"Uzbekistan","iso2"=>"UZ","iso3"=>"UZB","phone_code"=>"998","deleted_at"=>null],
            ["id"=>239,"nombre"=>"Vanuatu","name"=>"Vanuatu","iso2"=>"VU","iso3"=>"VUT","phone_code"=>"678","deleted_at"=>null],
            ["id"=>240,"nombre"=>"Venezuela","name"=>"Venezuela","iso2"=>"VE","iso3"=>"VEN","phone_code"=>"58","deleted_at"=>null],
            ["id"=>241,"nombre"=>"Vietnam","name"=>"Vietnam","iso2"=>"VN","iso3"=>"VNM","phone_code"=>"84","deleted_at"=>null],
            ["id"=>242,"nombre"=>"Wallis y Futuna","name"=>"Wallis and Futuna","iso2"=>"WF","iso3"=>"WLF","phone_code"=>"681","deleted_at"=>null],
            ["id"=>243,"nombre"=>"Yemen","name"=>"Yemen","iso2"=>"YE","iso3"=>"YEM","phone_code"=>"967","deleted_at"=>null],
            ["id"=>244,"nombre"=>"Yibuti","name"=>"Djibouti","iso2"=>"DJ","iso3"=>"DJI","phone_code"=>"253","deleted_at"=>null],
            ["id"=>245,"nombre"=>"Zambia","name"=>"Zambia","iso2"=>"ZM","iso3"=>"ZMB","phone_code"=>"260","deleted_at"=>null],
            ["id"=>246,"nombre"=>"Zimbabue","name"=>"Zimbabwe","iso2"=>"ZW","iso3"=>"ZWE","phone_code"=>"263","deleted_at"=>null]
        ];

        Country::create($countries);
    }
}
