import "./base";
import "./preventContextMenu";
import "./vIdle";
import "./swal2";
import "./lazyImput";
import "./validation";
import "./vue-head";
import "./globalFilters";
import "./vue-diagonal";
